import type { Metadata } from "next";
import { Blinker } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const blinker = Blinker({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Minimaru E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blinker.className} w-full scroll-smooth`}>
        <div className="shadow-md w-full sticky top-0 bg-white z-20">
          <Navbar />
        </div>
        <div className="max-w-[1200px] mx-auto my-0 px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
